# This is a basic workflow to help you get started with Actions

name: ${{ github.actor }} GitHub Actions test

env: 
  GITHUB_ACTIONS: true
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  github-task-job: 
    runs-on: ubuntu-latest

    steps: 
      - name: Show GITHUB_ACTIONS variable
        run: echo "GITHUB_ACTIONS=${{ env.GITHUB_ACTIONS }}"

      - name: Show Branch and Repo
        run: |
          echo "Branch: ${{ github.ref }} "
          echo "Repository: ${{ github.repository }}"

      - name: Show event name
        run: 'echo "Event: ${{ github.event_name }}"'
            
      
